### ISSUE TITLE
trouble with the installation

### ISSUE THREAD

**Issue by KKimj** [MichalKacprzak99/jarvis#1]
Hello,
I'm having trouble with the installation.
I want to use this good package on Windows.
Can I use it in Maxos or Linux?

Thanks!

```
$ pip install jarvis-assistant
```

```
C:\Users>pip install jarvis-assistant
Collecting jarvis-assistant
  Using cached jarvis_assistant-0.1.3-py3-none-any.whl (9.6 kB)
Collecting pyttsx3
  Using cached pyttsx3-2.90-py3-none-any.whl (39 kB)
Collecting python-dotenv
  Using cached python_dotenv-0.17.1-py2.py3-none-any.whl (18 kB)
Collecting textblob
  Using cached textblob-0.15.3-py2.py3-none-any.whl (636 kB)
Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting SpeechRecognition
  Using cached SpeechRecognition-3.8.1-py2.py3-none-any.whl (32.8 MB)
Collecting pyjokes==0.6.0
  Using cached pyjokes-0.6.0-py2.py3-none-any.whl (26 kB)
Collecting gTTS
  Using cached gTTS-2.2.2-py3-none-any.whl (25 kB)
Collecting pymongo
  Using cached pymongo-3.11.4-cp39-cp39-win_amd64.whl (383 kB)
Collecting wikipedia
  Using cached wikipedia-1.4.0.tar.gz (27 kB)
Collecting nltk
  Using cached nltk-3.6.2-py3-none-any.whl (1.5 MB)
Collecting numpy
  Using cached numpy-1.20.2-cp39-cp39-win_amd64.whl (13.7 MB)
Collecting pytemperature
  Using cached pytemperature-1.0.zip (2.2 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ziun7\appdata\local\programs\python\python39\python3.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ziun7\\AppData\\Local\\Temp\\pip-install-bkv5jdzx\\pytemperature_1b4ca0066b82444e9f799c93761b432f\\setup.py'"'"'; __file__='"'"'C:\\Users\\ziun7\\AppData\\Local\\Temp\\pip-install-bkv5jdzx\\pytemperature_1b4ca0066b82444e9f799c93761b432f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ziun7\AppData\Local\Temp\pip-pip-egg-info-0u8et_j6'
         cwd: C:\Users\ziun7\AppData\Local\Temp\pip-install-bkv5jdzx\pytemperature_1b4ca0066b82444e9f799c93761b432f\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ziun7\AppData\Local\Temp\pip-install-bkv5jdzx\pytemperature_1b4ca0066b82444e9f799c93761b432f\setup.py", line 16, in <module>
        long_description=(read('README.txt')),
      File "C:\Users\ziun7\AppData\Local\Temp\pip-install-bkv5jdzx\pytemperature_1b4ca0066b82444e9f799c93761b432f\setup.py", line 5, in read
        return f.read()
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b3/7a/6d1aa5434b2272122aa4e72354c03fdfa0202ea74f1c1fa4cbbfe0f6ba3d/pytemperature-1.0.zip#sha256=8b8245bc78354cf050ed9e1640fd2a8a2d2f22438959cc018f651c0c5d16fb4f (from https://pypi.org/simple/pytemperature/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting jarvis-assistant
  Using cached jarvis_assistant-0.1.2-py3-none-any.whl (9.6 kB)
  Using cached jarvis_assistant-0.1.1-py3-none-any.whl (9.2 kB)
  Using cached jarvis_assistant-0.1-py3-none-any.whl (8.9 kB)
ERROR: Cannot install jarvis-assistant==0.1, jarvis-assistant==0.1.1, jarvis-assistant==0.1.2 and jarvis-assistant==0.1.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    jarvis-assistant 0.1.3 depends on pytemperature
    jarvis-assistant 0.1.2 depends on pytemperature
    jarvis-assistant 0.1.1 depends on pytemperature
    jarvis-assistant 0.1 depends on pytemperature

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

```

**Comment by lishuoiscas** [comment]
Hi, KKimj, it has declared that it supports win engine at its metadata info" Operating System :: Microsoft :: Windows". You may check your python version whether it satisfies "Requires-Python: >=3.6". 
If it works, please let me know. Hope you all the well.

**Comment by KKimj** [comment]
Hi @lishuoiscas 
Thanks your comment!
Have a nice day!
thanks

**Comment by lishuoiscas** [comment]
Have solved this problem? If possible, I wanna know how you solved it. Thanks~
